version: "3"

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: ghcr.io/mizunashi-mana/sharkey-ppa-source/runner
        depends_on:
            - redis
            - postgres
        ports:
            - "3000:3000"
        networks:
            - internal-net
        volumes:
            - ./docker/config.yml:/etc/sharkey/config.yml:ro
            - app-files:/var/lib/sharkey/files

    redis:
        image: docker.io/redis:7.0-alpine
        networks:
            - internal-net
        volumes:
            - redis-data:/data

    postgres:
        image: docker.io/postgres:15-alpine
        networks:
            - internal-net
        env_file:
            - ./docker/postgres.env
        volumes:
            - postgres-data:/var/lib/postgresql/data

networks:
    internal-net:

volumes:
    app-files:
    redis-data:
    postgres-data:
