#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

mkdir -p "$(dirname "$1")"
OUTPUT_FILE="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"

SRC_DIR="$(dirname "$OUTPUT_FILE")/orig_src"
mkdir -p "$(dirname "$SRC_DIR")"

git clone \
    --branch "$GIT_COMMIT_REF" \
    --depth 1 \
    "$GIT_REPO" "$SRC_DIR"

cd "$SRC_DIR" && git submodule update --init --recursive --depth 1
rm -rf "$SRC_DIR/.git" "$SRC_DIR"/*/.git

tar -C "$SRC_DIR" -czf "$OUTPUT_FILE" .
