#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
eval "$("$SCRIPT_DIR/init-bash-source")"

GITHUB_TAG_NAME="$1"
PKG_VERSION_MAIN="$(echo "$GITHUB_TAG_NAME" | sed -E 's/^v([^-]+)-.*$/\1/')"

[ "$PKG_VERSION_DEB_MAIN" = "$PKG_VERSION_MAIN" ]
